alias vimrc='nvim ~/.config/nvim/init.vim'
alias lg='lazygit'
alias cdvim='cd ~/.config/nvim'
alias cddconf='cd ~/.dconf'
alias oh='dolphin --new-window ~ &'
alias rr='ranger ~'
alias oc='dolphin --new-window . &'
